### ISSUE TITLE
Ambiguity between same member with linked source file.

### ISSUE THREAD

**Issue by srivatsn** [dotnet/roslyn-project-system#1030]
Reported through [VS Feedback](https://developercommunity.visualstudio.com/content/problem/2482/ambiguity-between-same-member-with-linked-source-f.html)

If a source file is added as a link in a .Net Standard library, all references to members inside the source file (class source file) all have the issue of "Ambiguity between 'Class.Member' and 'Class.Member'". If the member definition name is changed, and the source file is saved, the error disappears and the error that no member with that name exists appears (meaning that there is only a single definition of the member in the whole project). If the same file is load in via normal copying, the error doesn't occur. 

Project that shows the repro is [here](https://developercommunity.visualstudio.com/storage/attachments/373-20161120ambiguity.zip)

**Comment by srivatsn** [comment]
I can repro this. The compiler builds fine and this only happens in the IDE. When I look at the design time build log it's passing only that one linked file to compiler. I think there's a bug in our LS host that's causing us to send the same linked file twice to the language service.  If I simply have another copy of this file in a regular project I see the ambiguity error in copy and a whole bunch of squiggles about redefinition in the other copy. So my guess is that the LS has two copies of this file and the copy with the redefinition errors are being ignored and not sent to the error list.

**Comment by mavasani** [comment]
Dupe of https://github.com/dotnet/roslyn-project-system/issues/986?

**Comment by srivatsn** [comment]
Could be - can you please take a look?

**Comment by mavasani** [comment]
This is indeed a dupe of #986. Repro is even simpler - just add a source file to your project from any parent OR sibling directory of the project directory (need not be a linked file) and you will see duplicate member results.

```
<Compile Include="..\Class1.cs" />
```

Seems like we are receiving more than one evaluations with same source file added. Investigating..

**Comment by mavasani** [comment]
Ah seems like we receive 2 evaluations with following paths:

1. `%root%\Class1.cs`
2. `%root%\ClassLibrary1\..\Class1.cs`

We have a hash set of added source files in our SourceItemHandler, but that caches the provided paths in the CPS update, not the normalized paths.

**Comment by myyandar** [comment]
this problem is still biting developers but the is closed. And no solution?

**Comment by jmarolf** [comment]
@myyandar could you file a new bug with repro steps for you issue?  We believe this was fixed with this pull request: https://github.com/dotnet/project-system/pull/1032

**Comment by Darker** [comment]
This is still not fixed. I cannot send the entire project as a repro, but I'm having the exact same issue - all properties are marked as ambiguous, but the error references the same property.

**Comment by drewnoakes** [comment]
@Darker could you create a new minimal solution that reproduces the issue you're seeing?

**Comment by elmerhd** [comment]
it's 2020 and still not yet fixed 😢

**Comment by davkean** [comment]
It's very unlikely you are hitting this exact bug. Please report a problem via Help -> Send Feedback -> Report a Problem.

**Comment by ex1dreamer** [comment]
I'm getting the same error/issue with system.drawing. bitmap referenced by few cross-referenced projects in one solution
