### ISSUE TITLE
VS2017 RC3: Failure to update many projects from project.json to csproj

### ISSUE THREAD

**Issue by niemyjski** [dotnet/roslyn-project-system#1443]
##Repro steps:

git clone https://github.com/exceptionless/Exceptionless.Net

Open the .sln file in VS 2017 RC3
Migrate the project.json based projects to .csproj.

##Expected Results

The migration should succeed.

##Actual Results

UpgradeLog.htm.txt

Many projects fail to upgrade

**Comment by davkean** [comment]
https://github.com/exceptionless/Exceptionless.Net/commit/31ef359ae1f778c7c0a39a268323ad1f3c12381a

**Comment by davkean** [comment]
Thanks, we'll take a look.

**Comment by 333fred** [comment]
RC3 was affected by this bug: https://github.com/dotnet/roslyn-project-system/issues/1376. Confirmed the issue does not repro on latest internal builds, I have a clean migration report.

However, I am not seeing a NuGet restore getting kicked off for the project, build is complaining about missing `package.assets.json`. @srivatsn @natidea

**Comment by 333fred** [comment]
I'm going to close this issue, since the original problem is fixed. The NuGet issue appears to be the same one filed by @krwq: https://github.com/dotnet/roslyn-project-system/issues/1447.

**Comment by niemyjski** [comment]
This is still broken, my project upgrades in the latest build but the compiler directives are lost on a per framework basis (only some of them are copied).


```
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard1.2' ">
    <DefineConstants>$(DefineConstants);NO_SQL_CLIENT;NETSTANDARD;NETSTANDARD1_2</DefineConstants>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard1.3' ">
    <DefineConstants>$(DefineConstants);NETSTANDARD1_3</DefineConstants>
  </PropertyGroup>
```

Both of them should have `NO_SQL_CLIENT` and `NETSTANDARD`
