### ISSUE TITLE
Output type in AppDesigner is wrong for Console Application

### ISSUE THREAD

**Issue by davkean** [dotnet/roslyn-project-system#814]
1. Create new Console App (.NET Core)
2. Open AppDesigner

Expected: Output type "Console Application"
Actual: Output type "Windows Application"

I suspect this has also broken this:

1. In AppDesigner, change Output type to "Class Library"

Expected: For Win32/Manifest properties to be disabled
Actual: They are enabled

**Comment by davkean** [comment]
I suspect this is caused by: https://github.com/dotnet/roslyn-project-system/issues/813

**Comment by davkean** [comment]
@jinujoseph This was fixed by your revert? This looks very different.

**Comment by jinujoseph** [comment]
you are right , just tested this d15rel/15.0.26005.1
This is still broken. Weird it's working fine on my dev hive . I will try on clean machine

**Comment by RaulPerez1** [comment]
This is a dupe of #813

**Comment by jnm2** [comment]
ICreating a .NET Standard class library also shows in the app designer as output type "Windows Application" in 15.0.26014.0. In spite of that it's building correctly, so am I right in thinking that class library output is the default and that I don't need to be manually specifying it in the .csproj?

**Comment by davkean** [comment]
Yes, this is just this bug. The designer is wrong - class library is the default.
