### ISSUE TITLE
Project reload prompt after saving project file in editor.

### ISSUE THREAD

**Issue by AArnott** [dotnet/roslyn-project-system#880]
VS: d15prerel 26005.5

1. Create a new .NET Core console app
1. Edit the project in the editor (while the project remains open)
1. Change TargetFramework property to TargetFrameworks (add an 's'). Save the file.

**Expected**
The project picks up the change immediately without a prompt.

**Actual**
I see this prompt first:

![image](https://cloud.githubusercontent.com/assets/3548/20916340/21d20cee-bb40-11e6-9f7d-e565a27b0541.png)

**Comment by davkean** [comment]
This looks like a known regression in MSBuild that is being fixed right now. @333fred is this caused by the same one?

**Comment by 333fred** [comment]
Yeah, this is the same bug as we were talking about offline. It's fixed by this pull: https://github.com/Microsoft/msbuild/pull/1446. With @rainersigwald's latest private, I no longer see it.

**Comment by srivatsn** [comment]
Closing since this is fixed by https://github.com/Microsoft/msbuild/pull/1446

**Comment by dsplaisted** [comment]
I'm still seeing this, on d15prerel 26020.2, with MSBuild binaries copied over from a locally-built copy of the latest version of the MSBuild xplat branch.  The reload prompt shows up whether you edit and save the project file in the VS editor or outside of VS.

**Comment by srivatsn** [comment]
@333fred can you take a look - maybe a different msbuild exception?

**Comment by 333fred** [comment]
Hmm. I'm not seeing this on 26019.5, with no external changes. I'll try updating in a bit.

**Comment by 333fred** [comment]
I'm not seeing this on 26029.01.

**Comment by 333fred** [comment]
@dsplaisted and I talked offline, it's not reproing.
